<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260621204234 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Modelo de datos inicial de MANKA: user, device, issue_category, issue, issue_technician, observation, api_token.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE api_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, token VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7BA2F5EB5F37A13B ON api_token (token)');
        $this->addSql('CREATE TABLE device (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE issue (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, type VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, category_id INT NOT NULL, device_id INT NOT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_12AD233E12469DE2 ON issue (category_id)');
        $this->addSql('CREATE INDEX IDX_12AD233E94A4C7D4 ON issue (device_id)');
        $this->addSql('CREATE INDEX IDX_12AD233EB03A8386 ON issue (created_by_id)');
        $this->addSql('CREATE TABLE issue_technician (issue_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (issue_id, user_id))');
        $this->addSql('CREATE INDEX IDX_640C92145E7AA58C ON issue_technician (issue_id)');
        $this->addSql('CREATE INDEX IDX_640C9214A76ED395 ON issue_technician (user_id)');
        $this->addSql('CREATE TABLE issue_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE observation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, issue_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C576DBE05E7AA58C ON observation (issue_id)');
        $this->addSql('CREATE INDEX IDX_C576DBE0F675F31B ON observation (author_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, name VARCHAR(255) NOT NULL, surname VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL, last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_email ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE issue ADD CONSTRAINT FK_12AD233E12469DE2 FOREIGN KEY (category_id) REFERENCES issue_category (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE issue ADD CONSTRAINT FK_12AD233E94A4C7D4 FOREIGN KEY (device_id) REFERENCES device (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE issue ADD CONSTRAINT FK_12AD233EB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE issue_technician ADD CONSTRAINT FK_640C92145E7AA58C FOREIGN KEY (issue_id) REFERENCES issue (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE issue_technician ADD CONSTRAINT FK_640C9214A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE observation ADD CONSTRAINT FK_C576DBE05E7AA58C FOREIGN KEY (issue_id) REFERENCES issue (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE observation ADD CONSTRAINT FK_C576DBE0F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE issue DROP CONSTRAINT FK_12AD233E12469DE2');
        $this->addSql('ALTER TABLE issue DROP CONSTRAINT FK_12AD233E94A4C7D4');
        $this->addSql('ALTER TABLE issue DROP CONSTRAINT FK_12AD233EB03A8386');
        $this->addSql('ALTER TABLE issue_technician DROP CONSTRAINT FK_640C92145E7AA58C');
        $this->addSql('ALTER TABLE issue_technician DROP CONSTRAINT FK_640C9214A76ED395');
        $this->addSql('ALTER TABLE observation DROP CONSTRAINT FK_C576DBE05E7AA58C');
        $this->addSql('ALTER TABLE observation DROP CONSTRAINT FK_C576DBE0F675F31B');
        $this->addSql('DROP TABLE api_token');
        $this->addSql('DROP TABLE device');
        $this->addSql('DROP TABLE issue');
        $this->addSql('DROP TABLE issue_technician');
        $this->addSql('DROP TABLE issue_category');
        $this->addSql('DROP TABLE observation');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
