<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260325112905 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE issue_category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE issue DROP CONSTRAINT fk_12ad233ec54c8c93');
        $this->addSql('ALTER TABLE issue DROP CONSTRAINT fk_12ad233e94a4c7d4');
        $this->addSql('DROP TABLE issue');
        $this->addSql('DROP TABLE issue_type');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE issue (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date TIMESTAMP(0) WITH TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, completed BOOLEAN NOT NULL, hygiene BOOLEAN NOT NULL, description TEXT NOT NULL, type_id INT NOT NULL, device_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_12ad233ec54c8c93 ON issue (type_id)');
        $this->addSql('CREATE INDEX idx_12ad233e94a4c7d4 ON issue (device_id)');
        $this->addSql('CREATE TABLE issue_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE issue ADD CONSTRAINT fk_12ad233ec54c8c93 FOREIGN KEY (type_id) REFERENCES issue_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE issue ADD CONSTRAINT fk_12ad233e94a4c7d4 FOREIGN KEY (device_id) REFERENCES device (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP TABLE issue_category');
    }
}
